/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopcem;

import model.Programas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ProgramaEstudio;

/**
 *
 * @author JoseFa
 */
public class ListarProgramas extends javax.swing.JFrame {

    Programas programas = new Programas();

    /**
     * Creates new form PublicarPrograma
     */
    public ListarProgramas() {
        initComponents();
        anadirColumnaTabla();
    }

    public ArrayList ListarProgramas2() {
        try {
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "montreal", "montreal");
            Statement stmt = con.createStatement();
            String sql = "SELECT p.nombre_programa, p.descripcion, p.duracion, p.cant_min_alumnos, p.cant_max_alumnos, e.estado\n"
                    + "from PROGRAMA_ESTUDIO_CEM p JOIN ESTADO e \n"
                    + "ON p.fk_id_estado = e.id_estado";
            ResultSet rst;
            rst = stmt.executeQuery(sql);

            ArrayList<ProgramaEstudio> listProgramas = new ArrayList<>();
            while (rst.next()) {
                ProgramaEstudio progr = new ProgramaEstudio(rst.getString("nombre_programa"), rst.getString("descripcion"), rst.getString("duracion"), rst.getInt("cant_min_alumnos"), rst.getInt("cant_max_alumnos"), rst.getString("estado"));
                //Programas progr = new Programas(rst.getInt("id_programa"), rst.getString("nombre_programa"), rst.getString("descripcion"), rst.getInt("fk_id_estado"));
                //System.out.println(progr.getNombre() + " " + progr.getEstado());
                listProgramas.add(progr);
            }
            return listProgramas;

        } catch (SQLException e) {
            System.out.println(e);
        }
        return null;
    }

    public void anadirColumnaTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<ProgramaEstudio> lista = ListarProgramas2();
        Object rowData[] = new Object[6];
        for (int i = 0; i < lista.size(); i++) {
            rowData[0] = lista.get(i).getNombre();
            rowData[1] = lista.get(i).getDescripcion();
            rowData[2] = lista.get(i).getDuracion();
            rowData[3] = lista.get(i).getCantMin();
            rowData[4] = lista.get(i).getCantMax();
            rowData[5] = lista.get(i).getEstado();
            model.addRow(rowData);
        }
    }

    public String indexSeleccionado() {
        String selectedData = null;

        int[] selectedRow = jTable1.getSelectedRows();
        int[] selectedColumns = jTable1.getSelectedColumns();
        try {
            for (int i = 0; i < selectedRow.length; i++) {
                for (int j = 0; j < selectedColumns.length; j++) {
                    selectedData = (String) jTable1.getValueAt(selectedRow[i], selectedColumns[j]);
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Seleccione el nombre del programa que desee modificar");
        }
        System.out.println("Selected: " + selectedData);
        return selectedData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnPublicar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnNoPublicar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Duracion", "Cant. Minima Alumnos", "Cant. Maxima Alumnos", "Estado"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Programas de Estudio CEM");

        btnPublicar.setText("Publicar");
        btnPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnNoPublicar.setText("No publicar");
        btnNoPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoPublicarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoCEM1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(301, 301, 301)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNoPublicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPublicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVolver)
                            .addComponent(jLabel1))
                        .addGap(3, 3, 3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnPublicar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNoPublicar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnEliminar))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        new CrearPE().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "montreal", "montreal");
            Statement stmt = con.createStatement();
            String index = indexSeleccionado();
            //System.out.println(index);
            //query     

            //StringBuilder sb = new StringBuilder();
            //sb.append("SELECT p.nombre_programa, p.descripcion, p.duracion, p.cant_min_alumnos, p.cant_max_alumnos, e.estado\n");
            //sb.append("from PROGRAMA_ESTUDIO_CEM p JOIN ESTADO e\n");
            //sb.append("ON p.fk_id_estado = e.id_estado");
            //sb.append(String.format("WHERE algo = '$1%s'", 2));
            //ResultSet rs = stmt.executeQuery(sb.toString());
            ResultSet rs = stmt.executeQuery("select * from programa_estudio_cem where NOMBRE_PROGRAMA = '" + index + "' OR DESCRIPCION = '" + index + "'");
            while (rs.next()) {
                //System.out.println(rs.getInt(1) + " " + rs.getString(2) + " " + rs.getString(3));
                String sql = "UPDATE programa_estudio_cem SET FK_ID_ESTADO = 16 WHERE NOMBRE_PROGRAMA = '" + index + "' OR DESCRIPCION = '" + index + "'";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Programa publicado con exito");
                new Menu().setVisible(true);
                dispose();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnPublicarActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1FocusGained

    private void btnNoPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoPublicarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "montreal", "montreal");
            Statement stmt = con.createStatement();
            String index = indexSeleccionado();
            //System.out.println(index);
            //query     
            ResultSet rs = stmt.executeQuery("select * from programa_estudio_cem where NOMBRE_PROGRAMA = '" + index + "' OR DESCRIPCION = '" + index + "'");
            while (rs.next()) {
                //System.out.println(rs.getInt(1) + " " + rs.getString(2) + " " + rs.getString(3));
                String sql = "UPDATE programa_estudio_cem SET FK_ID_ESTADO = 17 WHERE NOMBRE_PROGRAMA = '" + index + "' OR DESCRIPCION = '" + index + "'";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Programa ya no esta publicado");
                new Menu().setVisible(true);
                dispose();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnNoPublicarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "montreal", "montreal");
            Statement stmt = con.createStatement();
            String index = indexSeleccionado();
            //System.out.println(index);
            //query     
            ResultSet rs = stmt.executeQuery("select * from programa_estudio_cem where NOMBRE_PROGRAMA = '" + index + "' OR DESCRIPCION = '" + index + "'");
            while (rs.next()) {
                //System.out.println(rs.getInt(1) + " " + rs.getString(2) + " " + rs.getString(3));
                String sql = "DELETE FROM programa_estudio_cem WHERE NOMBRE_PROGRAMA = '" + index + "' OR DESCRIPCION = '" + index + "'";
                PreparedStatement pstmt = con.prepareStatement(sql);
                int dialogButton = JOptionPane.showConfirmDialog(null, "Eliminar programa?");
                if (dialogButton == 0) {
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Programa Eliminado");
                    new Menu().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Programa No Eliminado");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNoPublicar;
    private javax.swing.JButton btnPublicar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
