/*------------------------------------------------------------------------------------------------------
----------------------------------------- Inserciones Tabla Ciudades -----------------------------------
------------------------------------------------------------------------------------------------------*/

INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Berlín',3);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Múnich',3);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Frankfurt',3);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Hamburgo',3);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Colonia',3);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Stuttgart',3);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Núremberg',3);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Buenos Aires',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Córdoba',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Rosario',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Mendoza',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'La Plata',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Miguel de Tucumán',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Mar del Plata',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Salta',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Santa Fe',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Juan',9);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Canberra',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Sídney',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Melbourne',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Brisbane',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Perth',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Adelaide',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Gold Coast',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Newcastle',11);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Viena',12);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Bruselas',18);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Brujas',18);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Sucre',23);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'La Paz',23);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Brasilia',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'São Paulo',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Río de Janeiro',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Brasilia',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Salvador de Bahía',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Belo Horizonte',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Fortaleza',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Curitiba',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Porto Alegre',26);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ottawa',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Toronto',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Montreal',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Vancouver',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Quebec',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Calgary',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Edmonton',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Winnipeg',35);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Santiago',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Concepción',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Valparaíso',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'La Serena',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Antofagasta',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Temuco',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Rancagua',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Iquique',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Talca',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Arica',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Puerto Mont',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Los Ángeles',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Calama',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Copiapó',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Osorno',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Valdivia',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Punta Arenas',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Curicó',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ovalle',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Linares',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Los Andes',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Melipilla',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Felipe',38);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Pekín',39);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Shanghái',39);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Lhasa',39);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Xi’an',39);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Bogotá',41);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Medellín',41);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Cali',41);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Barranquilla',41);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Cartagena',41);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Cúcuta',41);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Seúl',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Busan',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Incheon',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Daegu',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Daejeon',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Gwangju',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ulsan',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Suwon',45);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Madrid',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Barcelona',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Valencia',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Sevilla',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Zaragoza',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Málaga',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Murcia',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Palma de Mallorca',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Las Palmas',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Bilbao',59);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Nueva York',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Los Angeles',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Chicago',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Houston',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Philadelphia',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Phoenix',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Antonio',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Diego',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Dallas',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Jose',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Austin',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Indianapolis',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Jacksonville',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Francisco',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Columbus',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Palo Alto',);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Pasadena',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Cambridge',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Princeton',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Berkeley',60);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Roma',90);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Milán',90);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Nápoles',90);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Palermo',90);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Génova',90);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Bolonia',90);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Florencia'90,);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Tokyo',91);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Kyoto',91);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Osaka',91);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Sapporo',91);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Fukuoka',91);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Hiroshima'91,);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Kobe',91);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Nagasaki',91);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Luxemburgo',108);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ciudad de México',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ecatepec',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Guadalajara',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Puebla de Zaragoza',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ciudad Juárez',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Tijuana',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'León',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Zapopan',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Monterrey',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Nezahualcóyotl',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Chihuahua',119);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Oslo',133);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Bergen',133);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Trondheim',133);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Tromso',133);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Lillehamer',133);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Molde',133);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Larvik',133);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Auckland',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Manukau',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'North Shore City',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Waitakere',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Wellington',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Hamilton',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Tauranga',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Dunedin',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Lower Hutt',134);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Asunción',142);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ciudad del Este',142);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Luque',142);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Lorenzo',142);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Capiatá',142);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Lima',143);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Arequipa',143);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Trujillo',143);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Chiclayo',143);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Londres',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Oxford',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Birmingham',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Glasgow',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Liverpool',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Leeds',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Edimburgo',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Bristol',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Cambridge',146);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Moscú',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'San Petersburgo',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Novosibirsk',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ekaterimburgo',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Nizhni Nóvgorod',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Samara',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Omsk',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Kazán',153);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Singapur',164);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Estocolmo',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Gotemburgo',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Malmö',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Upsala',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Västerås',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Örebro',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Linköping',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Helsingborg',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Jönköping',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Norrköping',172);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Zurich',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Lausanne',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ginebra',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Lucerna',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Basilea',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Locarno',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Lugano',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Berna',173);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Estambul',185);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ankara',185);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Esmirna',185);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Antalya',185);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Bursa',185);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Montevideo',189);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Ciudad de la Costa',189);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Salto',189);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Paysandú',189);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Maldonado',189);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Rivera',189);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Las Piedras',189);
INSERT INTO ciudad VALUES (ciudadesSeq.NEXTVAL,'Tacuarembó',189);

