/*------------------------------------------------------------------------------------------------------
----------------------------------------- Inserciones Tabla Ciudades -----------------------------------
------------------------------------------------------------------------------------------------------*/

INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Berlín',3);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Múnich',3);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Frankfurt',3);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Hamburgo',3);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Colonia',3);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Stuttgart',3);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Núremberg',3);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Buenos Aires',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Córdoba',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Rosario',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Mendoza',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'La Plata',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Miguel de Tucumán',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Mar del Plata',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Salta',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Santa Fe',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Juan',9);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Canberra',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Sídney',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Melbourne',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Brisbane',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Perth',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Adelaide',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Gold Coast',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Newcastle',11);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Viena',12);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Bruselas',18);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Brujas',18);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Sucre',23);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'La Paz',23);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Brasilia',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'São Paulo',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Río de Janeiro',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Brasilia',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Salvador de Bahía',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Belo Horizonte',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Fortaleza',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Curitiba',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Porto Alegre',26);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ottawa',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Toronto',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Montreal',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Vancouver',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Quebec',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Calgary',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Edmonton',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Winnipeg',35);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Santiago',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Concepción',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Valparaíso',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'La Serena',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Antofagasta',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Temuco',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Rancagua',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Iquique',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Talca',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Arica',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Puerto Mont',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Los Ángeles',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Calama',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Copiapó',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Osorno',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Valdivia',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Punta Arenas',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Curicó',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ovalle',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Linares',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Los Andes',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Melipilla',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Felipe',38);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Pekín',39);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Shanghái',39);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Lhasa',39);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Xi’an',39);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Bogotá',41);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Medellín',41);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Cali',41);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Barranquilla',41);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Cartagena',41);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Cúcuta',41);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Seúl',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Busan',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Incheon',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Daegu',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Daejeon',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Gwangju',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ulsan',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Suwon',45);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Madrid',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Barcelona',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Valencia',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Sevilla',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Zaragoza',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Málaga',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Murcia',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Palma de Mallorca',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Las Palmas',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Bilbao',59);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Nueva York',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Los Angeles',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Chicago',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Houston',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Philadelphia',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Phoenix',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Antonio',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Diego',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Dallas',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Jose',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Austin',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Indianapolis',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Jacksonville',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Francisco',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Columbus',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Palo Alto',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Pasadena',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Cambridge',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Princeton',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Berkeley',60);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Roma',90);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Milán',90);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Nápoles',90);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Palermo',90);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Génova',90);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Bolonia',90);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Florencia',90);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Tokyo',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Kyoto',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Osaka',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Sapporo',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Fukuoka',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Hiroshima',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Kobe',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Nagasaki',91);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Luxemburgo',108);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ciudad de México',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ecatepec',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Guadalajara',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Puebla de Zaragoza',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ciudad Juárez',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Tijuana',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'León',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Zapopan',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Monterrey',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Nezahualcóyotl',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Chihuahua',119);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Oslo',133);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Bergen',133);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Trondheim',133);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Tromso',133);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Lillehamer',133);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Molde',133);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Larvik',133);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Auckland',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Manukau',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'North Shore City',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Waitakere',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Wellington',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Hamilton',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Tauranga',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Dunedin',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Lower Hutt',134);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Asunción',142);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ciudad del Este',142);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Luque',142);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Lorenzo',142);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Capiatá',142);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Lima',143);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Arequipa',143);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Trujillo',143);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Chiclayo',143);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Londres',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Oxford',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Birmingham',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Glasgow',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Liverpool',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Leeds',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Edimburgo',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Bristol',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Cambridge',146);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Moscú',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'San Petersburgo',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Novosibirsk',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ekaterimburgo',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Nizhni Nóvgorod',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Samara',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Omsk',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Kazán',153);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Singapur',164);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Estocolmo',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Gotemburgo',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Malmö',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Upsala',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Västerås',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Örebro',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Linköping',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Helsingborg',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Jönköping',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Norrköping',172);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Zurich',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Lausanne',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ginebra',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Lucerna',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Basilea',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Locarno',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Lugano',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Berna',173);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Estambul',185);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ankara',185);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Esmirna',185);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Antalya',185);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Bursa',185);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Montevideo',189);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Ciudad de la Costa',189);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Salto',189);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Paysandú',189);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Maldonado',189);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Rivera',189);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Las Piedras',189);
INSERT INTO ciudad VALUES (ciudadSeq.NEXTVAL,'Tacuarembó',189);

