/*------------------------------------------------------------------------------------------------------
------------------------------------------- Inserciones Tabla Pais -------------------------------------
------------------------------------------------------------------------------------------------------*/

INSERT INTO pais VALUES (1,'Afganistán');
INSERT INTO pais VALUES (2,'Albania');
INSERT INTO pais VALUES (3,'Alemania');
INSERT INTO pais VALUES (4,'Andorra');
INSERT INTO pais VALUES (5,'Angola');
INSERT INTO pais VALUES (6,'Antigua y Barbuda');
INSERT INTO pais VALUES (7,'Arabia Saudita');
INSERT INTO pais VALUES (8,'Argelia');
INSERT INTO pais VALUES (9,'Argentina');
INSERT INTO pais VALUES (10,'Armenia');
INSERT INTO pais VALUES (11,'Australia');
INSERT INTO pais VALUES (12,'Austria');
INSERT INTO pais VALUES (13,'Azerbaiyán');
INSERT INTO pais VALUES (14,'Bahamas');
INSERT INTO pais VALUES (15,'Bangladés');
INSERT INTO pais VALUES (16,'Barbados');
INSERT INTO pais VALUES (17,'Baréin');
INSERT INTO pais VALUES (18,'Bélgica');
INSERT INTO pais VALUES (19,'Belice');
INSERT INTO pais VALUES (20,'Benín');
INSERT INTO pais VALUES (21,'Bielorrusia');
INSERT INTO pais VALUES (22,'Birmania');
INSERT INTO pais VALUES (23,'Bolivia');
INSERT INTO pais VALUES (24,'Bosnia-Herzegovina');
INSERT INTO pais VALUES (25,'Botsuana');
INSERT INTO pais VALUES (26,'Brasil');
INSERT INTO pais VALUES (27,'Brunéi');
INSERT INTO pais VALUES (28,'Bulgaria');
INSERT INTO pais VALUES (29,'Burkina Faso');
INSERT INTO pais VALUES (30,'Burundi');
INSERT INTO pais VALUES (31,'Bután');
INSERT INTO pais VALUES (32,'Cabo Verde');
INSERT INTO pais VALUES (33,'Camboya');
INSERT INTO pais VALUES (34,'Camerún');
INSERT INTO pais VALUES (35,'Canadá');
INSERT INTO pais VALUES (36,'Catar');
INSERT INTO pais VALUES (37,'Chad');
INSERT INTO pais VALUES (38,'Chile');
INSERT INTO pais VALUES (39,'China');
INSERT INTO pais VALUES (40,'Chipre');
INSERT INTO pais VALUES (41,'Colombia');
INSERT INTO pais VALUES (42,'Comoras');
INSERT INTO pais VALUES (43,'Congo');
INSERT INTO pais VALUES (44,'Corea del Norte');
INSERT INTO pais VALUES (45,'Corea del Sur');
INSERT INTO pais VALUES (46,'Costa de Marfil');
INSERT INTO pais VALUES (47,'Costa Rica');
INSERT INTO pais VALUES (48,'Croacia');
INSERT INTO pais VALUES (49,'Cuba');
INSERT INTO pais VALUES (50,'Dinamarca');
INSERT INTO pais VALUES (51,'Dominica');
INSERT INTO pais VALUES (52,'Ecuador');
INSERT INTO pais VALUES (53,'Egipto');
INSERT INTO pais VALUES (54,'El Salvador');
INSERT INTO pais VALUES (55,'Emiratos Árabes Unidos');
INSERT INTO pais VALUES (56,'Eritrea');
INSERT INTO pais VALUES (57,'Eslovaquia');
INSERT INTO pais VALUES (58,'Eslovenia');
INSERT INTO pais VALUES (59,'España');
INSERT INTO pais VALUES (60,'Estados Unidos');
INSERT INTO pais VALUES (61,'Estonia');
INSERT INTO pais VALUES (62,'Etiopía');
INSERT INTO pais VALUES (63,'Filipinas');
INSERT INTO pais VALUES (64,'Finlandia');
INSERT INTO pais VALUES (65,'Fiyi');
INSERT INTO pais VALUES (66,'Francia');
INSERT INTO pais VALUES (67,'Gabón');
INSERT INTO pais VALUES (68,'Gambia');
INSERT INTO pais VALUES (69,'Georgia');
INSERT INTO pais VALUES (70,'Ghana');
INSERT INTO pais VALUES (71,'Granada');
INSERT INTO pais VALUES (72,'Grecia');
INSERT INTO pais VALUES (73,'Guatemala');
INSERT INTO pais VALUES (74,'Guinea');
INSERT INTO pais VALUES (75,'Guinea Ecuatorial');
INSERT INTO pais VALUES (76,'Guinea-Bisáu');
INSERT INTO pais VALUES (77,'Guyana');
INSERT INTO pais VALUES (78,'Haití');
INSERT INTO pais VALUES (79,'Honduras');
INSERT INTO pais VALUES (80,'Hungría');
INSERT INTO pais VALUES (81,'India');
INSERT INTO pais VALUES (82,'Indonesia');
INSERT INTO pais VALUES (83,'Irak');
INSERT INTO pais VALUES (84,'Irán');
INSERT INTO pais VALUES (85,'Irlanda');
INSERT INTO pais VALUES (86,'Islandia');
INSERT INTO pais VALUES (87,'Islas Marshall');
INSERT INTO pais VALUES (88,'Islas Salomón');
INSERT INTO pais VALUES (89,'Israel');
INSERT INTO pais VALUES (90,'Italia');
INSERT INTO pais VALUES (91,'Jamaica');
INSERT INTO pais VALUES (92,'Japón');
INSERT INTO pais VALUES (93,'Jordania');
INSERT INTO pais VALUES (94,'Kazajistán');
INSERT INTO pais VALUES (95,'Kenia');
INSERT INTO pais VALUES (96,'Kirguistán');
INSERT INTO pais VALUES (97,'Kiribati');
INSERT INTO pais VALUES (98,'Kosovo');
INSERT INTO pais VALUES (99,'Kuwait');
INSERT INTO pais VALUES (100,'Laos');
INSERT INTO pais VALUES (101,'Lesoto');
INSERT INTO pais VALUES (102,'Letonia');
INSERT INTO pais VALUES (103,'Líbano');
INSERT INTO pais VALUES (104,'Liberia');
INSERT INTO pais VALUES (105,'Libia');
INSERT INTO pais VALUES (106,'Liechtenstein');
INSERT INTO pais VALUES (107,'Lituania');
INSERT INTO pais VALUES (108,'Luxemburgo');
INSERT INTO pais VALUES (109,'Macedonia');
INSERT INTO pais VALUES (110,'Madagascar');
INSERT INTO pais VALUES (111,'Malasia');
INSERT INTO pais VALUES (112,'Malaui');
INSERT INTO pais VALUES (113,'Maldivas');
INSERT INTO pais VALUES (114,'Malí');
INSERT INTO pais VALUES (115,'Malta');
INSERT INTO pais VALUES (116,'Marruecos');
INSERT INTO pais VALUES (117,'Mauricio');
INSERT INTO pais VALUES (118,'Mauritania');
INSERT INTO pais VALUES (119,'México');
INSERT INTO pais VALUES (120,'Micronesia');
INSERT INTO pais VALUES (121,'Moldavia');
INSERT INTO pais VALUES (123,'Mónaco');
INSERT INTO pais VALUES (124,'Mongolia');
INSERT INTO pais VALUES (125,'Montenegro');
INSERT INTO pais VALUES (126,'Mozambique');
INSERT INTO pais VALUES (127,'Namibia');
INSERT INTO pais VALUES (128,'Nauru');
INSERT INTO pais VALUES (129,'Nepal');
INSERT INTO pais VALUES (130,'Nicaragua');
INSERT INTO pais VALUES (131,'Níger');
INSERT INTO pais VALUES (132,'Nigeria');
INSERT INTO pais VALUES (133,'Noruega');
INSERT INTO pais VALUES (134,'Nueva Zelanda');
INSERT INTO pais VALUES (135,'Omán');
INSERT INTO pais VALUES (136,'Países Bajos');
INSERT INTO pais VALUES (137,'Pakistán');
INSERT INTO pais VALUES (138,'Palaos');
INSERT INTO pais VALUES (139,'Palestina');
INSERT INTO pais VALUES (140,'Panamá');
INSERT INTO pais VALUES (141,'Papúa Nueva Guinea');
INSERT INTO pais VALUES (142,'Paraguay');
INSERT INTO pais VALUES (143,'Perú');
INSERT INTO pais VALUES (144,'Polonia');
INSERT INTO pais VALUES (145,'Portugal');
INSERT INTO pais VALUES (146,'Reino Unido');
INSERT INTO pais VALUES (147,'República Centroafricana');
INSERT INTO pais VALUES (148,'República Checa');
INSERT INTO pais VALUES (149,'República Democrática del Congo');
INSERT INTO pais VALUES (150,'República Dominicana');
INSERT INTO pais VALUES (151,'Ruanda');
INSERT INTO pais VALUES (152,'Rumania');
INSERT INTO pais VALUES (153,'Rusia');
INSERT INTO pais VALUES (154,'Samoa');
INSERT INTO pais VALUES (155,'San Cristóbal y Nieves');
INSERT INTO pais VALUES (156,'San Marino');
INSERT INTO pais VALUES (157,'San Vicente y las Granadinas');
INSERT INTO pais VALUES (158,'Santa Lucía');
INSERT INTO pais VALUES (159,'Santo Tomé y Príncipe');
INSERT INTO pais VALUES (160,'Senegal');
INSERT INTO pais VALUES (161,'Serbia');
INSERT INTO pais VALUES (162,'Seychelles');
INSERT INTO pais VALUES (163,'Sierra Leona');
INSERT INTO pais VALUES (164,'Singapur');
INSERT INTO pais VALUES (165,'Siria');
INSERT INTO pais VALUES (166,'Somalia');
INSERT INTO pais VALUES (167,'Sri Lanka');
INSERT INTO pais VALUES (168,'Suazilandia');
INSERT INTO pais VALUES (169,'Sudáfrica');
INSERT INTO pais VALUES (170,'Sudán');
INSERT INTO pais VALUES (171,'Sudán del Sur');
INSERT INTO pais VALUES (172,'Suecia');
INSERT INTO pais VALUES (173,'Suiza');
INSERT INTO pais VALUES (174,'Surinam');
INSERT INTO pais VALUES (175,'Tailandia');
INSERT INTO pais VALUES (176,'Taiwán');
INSERT INTO pais VALUES (177,'Tanzania');
INSERT INTO pais VALUES (178,'Tayikistán');
INSERT INTO pais VALUES (179,'Timor Oriental');
INSERT INTO pais VALUES (180,'Togo');
INSERT INTO pais VALUES (181,'Tonga');
INSERT INTO pais VALUES (182,'Trinidad y Tobago');
INSERT INTO pais VALUES (183,'Túnez');
INSERT INTO pais VALUES (184,'Turkmenistán');
INSERT INTO pais VALUES (185,'Turquía');
INSERT INTO pais VALUES (186,'Tuvalu');
INSERT INTO pais VALUES (187,'Ucrania');
INSERT INTO pais VALUES (188,'Uganda');
INSERT INTO pais VALUES (189,'Uruguay');
INSERT INTO pais VALUES (190,'Uzbekistán');
INSERT INTO pais VALUES (191,'Vanuatu');
INSERT INTO pais VALUES (192,'Vaticano');
INSERT INTO pais VALUES (193,'Venezuela');
INSERT INTO pais VALUES (194,'Vietnam');
INSERT INTO pais VALUES (195,'Yemen');
INSERT INTO pais VALUES (196,'Yibuti');
INSERT INTO pais VALUES (197,'Zambia');
INSERT INTO pais VALUES (198,'Zimbabue');
