/*------------------------------------------------------------------------------------------------------
------------------------------------------- Inserciones Tabla Pais -------------------------------------
------------------------------------------------------------------------------------------------------*/

INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Afganistán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Albania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Alemania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Andorra');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Angola');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Antigua y Barbuda');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Arabia Saudita');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Argelia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Argentina');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Armenia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Australia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Austria');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Azerbaiyán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bahamas');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bangladés');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Barbados');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Baréin');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bélgica');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Belice');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Benín');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bielorrusia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Birmania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bolivia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bosnia-Herzegovina');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Botsuana');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Brasil');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Brunéi');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bulgaria');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Burkina Faso');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Burundi');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Bután');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Cabo Verde');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Camboya');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Camerún');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Canadá');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Catar');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Chad');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Chile');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'China');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Chipre');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Colombia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Comoras');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Congo');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Corea del Norte');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Corea del Sur');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Costa de Marfil');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Costa Rica');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Croacia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Cuba');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Dinamarca');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Dominica');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Ecuador');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Egipto');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'El Salvador');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Emiratos Árabes Unidos');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Eritrea');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Eslovaquia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Eslovenia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'España');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Estados Unidos');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Estonia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Etiopía');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Filipinas');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Finlandia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Fiyi');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Francia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Gabón');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Gambia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Georgia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Ghana');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Granada');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Grecia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Guatemala');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Guinea');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Guinea Ecuatorial');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Guinea-Bisáu');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Guyana');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Haití');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Honduras');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Hungría');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'India');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Indonesia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Irak');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Irán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Irlanda');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Islandia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Islas Marshall');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Islas Salomón');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Israel');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Italia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Jamaica');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Japón');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Jordania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Kazajistán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Kenia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Kirguistán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Kiribati');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Kosovo');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Kuwait');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Laos');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Lesoto');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Letonia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Líbano');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Liberia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Libia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Liechtenstein');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Lituania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Luxemburgo');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Macedonia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Madagascar');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Malasia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Malaui');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Maldivas');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Malí');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Malta');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Marruecos');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Mauricio');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Mauritania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'México');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Micronesia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Moldavia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Mónaco');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Mongolia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Montenegro');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Mozambique');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Namibia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Nauru');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Nepal');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Nicaragua');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Níger');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Nigeria');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Noruega');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Nueva Zelanda');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Omán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Países Bajos');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Pakistán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Palaos');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Palestina');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Panamá');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Papúa Nueva Guinea');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Paraguay');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Perú');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Polonia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Portugal');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Reino Unido');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'República Centroafricana');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'República Checa');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'República Democrática del Congo');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'República Dominicana');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Ruanda');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Rumania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Rusia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Samoa');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'San Cristóbal y Nieves');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'San Marino');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'San Vicente y las Granadinas');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Santa Lucía');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Santo Tomé y Príncipe');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Senegal');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Serbia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Seychelles');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Sierra Leona');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Singapur');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Siria');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Somalia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Sri Lanka');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Suazilandia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Sudáfrica');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Sudán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Sudán del Sur');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Suecia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Suiza');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Surinam');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Tailandia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Taiwán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Tanzania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Tayikistán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Timor Oriental');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Togo');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Tonga');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Trinidad y Tobago');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Túnez');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Turkmenistán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Turquía');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Tuvalu');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Ucrania');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Uganda');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Uruguay');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Uzbekistán');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Vanuatu');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Vaticano');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Venezuela');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Vietnam');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Yemen');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Yibuti');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Zambia');
INSERT INTO pais VALUES (PaisSeq.NEXTVAL,'Zimbabue');